### ISSUE TITLE
Bug on world load: multiple execution of one script

### ISSUE THREAD

**Issue by Isax03** [replaceitem/carpet-discarpet#11]
When a world with a discarpet script is unloaded and then reloaded, every event isn't executed only one time but more times, because there is no destructor of events objects on world unload.

**Comment by replaceitem** [comment]
I dont really get what you mean, but i changed some stuff about events yesterday, because they didnt load properly when scripts loaded the first time, is that with the new version (1.4.21 in releases, i changed it yesterday but didnt increase version number) or an older one?
If its not the new one, maybe try re-downloading 1.4.21 and try it again.

**Comment by Isax03** [comment]
I think that the events aren't deattached from the endler, when you quit the world. I suggest you to speak with @BisUmTo; I explained him in Italian and he can explain much better the problem

**Comment by replaceitem** [comment]
Alright, i changed some stuff about the discord events, in 8f14831f828948f7a93e04f66c90a15b52e7ae68 but im not sure if that fixed this issue.
Its really weird what causes this, since i also got this situation where discord events executed twice (on a dedicated server though).
If you are able to reproduce events triggering twice, please tell me, i will also see what problems i will face...

**Comment by replaceitem** [comment]
As far as i know its fixes, if encountered again, just open a new issue
