### ISSUE TITLE
Unable to use Author id contained in the message on discord

### ISSUE THREAD

**Issue by Isax03** [replaceitem/carpet-discarpet#5]
Request to add author ID as parameter of __on_discord_message() function

**Comment by replaceitem** [comment]
That is indeed missing, but there are so many other things that could be needed, to the point where the event has a lot of parameters.
Thats why i already started completely redoing everything since a couple weeks. There will be custom values for channels, messages, users, ...
Then you can just query the id like this: user~'id'
So it works like with entities in scarpet.
I might be able to release a version this weekend

**Comment by Isax03** [comment]
user ~ 'id' doesn't work, neither author ~ 'id'

Il giorno ven 18 dic 2020 alle ore 08:26 replaceitem <
notifications@github.com> ha scritto:

**Comment by replaceitem** [comment]
Yes, currently the author is just the name as a string.
But im working on a big update atm, which will make that possible. Basicly all values are no longer just strings, but custom valies where you can query all sorts of things.

**Comment by replaceitem** [comment]
Fixed with the completely new system, see the new [docs](https://github.com/replaceitem/carpet-discarpet#documentation) and [download it](https://github.com/replaceitem/carpet-discarpet/releases/tag/1.16.x)
