### ISSUE TITLE
Wrong title and description of dc_emoji_from_id(id)

### ISSUE THREAD

**Issue by Isax03** [replaceitem/carpet-discarpet#8]
The title is dc_emoji_from_id(id), but when used in a script, it says that it requires 2 arguments. The first has to be a Server value.
But using this:
**`dc_emoji_from_id(dc_server_from_id('771811559256621086'), ':dice2:')`**
it returns `null` even if the custom emoji exists on that server.

P.S. Can you post an example using this function?

**Comment by replaceitem** [comment]
Oh yes, docs are wrong. Tho, the ID of an emojis is not the name, but a number like server or channel ids, but there is nowhere to get those in discord afaik. So now the function will return a list of emojis with that name if there is none with that id (normally thats only one element in the list, exept if there are multiple emojis with the same name)

here's an example:
```py
__on_discord_message(message) -> (
    emoji = dc_emoji_from_id(message~'server','customemoji'):0;
    dc_send_message(message~'channel','Custom emoji: ' + emoji~'mention_tag');
);
```

Fixed with ea2d4741de464b3e648bfae7bb6fac9989860811 and 24f339df0c7615be515126301575d1d9fffd66e9

**Comment by replaceitem** [comment]
Is in version 1.4.21 now

**Comment by Isax03** [comment]
You can get the Emoji ID manually writing **`\:emoji_name:`** in one of server channels that has custom emojis.
Example: `\:dice1:` writes `<:dice1:790336156621340692>` in the channel; The ID of emoji is 790336156621340692.
So you can get the Emoji value -> **`dc_emoji_from_id(dc_server_from_id('771811559256621086'),'790336156755165255')`**

**Comment by replaceitem** [comment]
Ah yeah that would be a way
Getting it by name should be much easier though
